alias e='grep -E'
alias h='history'
alias i='irssi'
alias l='ls -lah'
alias q='exit'
alias c='clear'
alias t="tmux -2"
alias ta="tmux attach"
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'
alias lk='gnome-screensaver-command -l'
alias off='sudo shutdown -P now'
alias offon='sudo shutdown -r now'
