#!/bin/bash

dotsdir=~/.dotfiles
olddir=~/.dotfiles_old
dotfiles=".inputrc .bashrc .bash_aliases .functions .gitconfig .tmux.conf .vimrc .vrapperrc"

mkdir -p $olddir
cd $dotsdir

for file in $dotfiles; do
  #move to olddir as backup if already exists and not a link
  if ! [ -h ~/$file ]; then
    mv ~/$file $olddir
    #create new home symlink
    ln -sfv $dotsdir/$file ~/$file
  fi
done

#TODO:
#check whether required folders are there first, echo status
#automate installation of shell utility scripts

#create symlinks with custom destinations
if ! [ -h ~/.cmus/rc  ]; then
  mv ~/.cmus/rc $olddir
  ln -sfv $dotsdir/rc ~/.cmus/rc
fi

echo "Installation complete"
